#!/usr/bin/env bash
# Prepare the Go2 assets for RMA training.
#
# Training uses the jagged Go2 scene generated by tools/make_jagged_scene.py,
# which lives in the unitree_mujoco model tree one directory above this repo:
#   ../unitree_mujoco/unitree_robots/go2/scene_jagged.xml
#
# Evaluation (rma.eval_gym) uses the Go2 model bundled with the gym-quadruped
# pip package, so nothing extra is needed there.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GO2_DIR="$(cd "${REPO_ROOT}/.." && pwd)/unitree_mujoco/unitree_robots/go2"

if [ ! -f "${GO2_DIR}/go2.xml" ]; then
  echo "[assets] Go2 model not found at ${GO2_DIR}/go2.xml"
  echo "[assets] Clone the unitree_mujoco repo one directory above RMALR, e.g.:"
  echo "         git clone https://github.com/unitreerobotics/unitree_mujoco \\"
  echo "             $(cd "${REPO_ROOT}/.." && pwd)/unitree_mujoco"
  exit 1
fi

echo "[assets] generating jagged scene -> ${GO2_DIR}/scene_jagged.xml"
python "${REPO_ROOT}/tools/make_jagged_scene.py" \
  --out "${GO2_DIR}/scene_jagged.xml"

echo "[assets] done."
